networks:
  wg-public:
    driver: bridge
  wg-private:
    driver: bridge
    internal: true

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard-single
    networks:
      - wg-public
      - wg-private
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=$ENV_TZ
      - SERVERURL=$ENV_SERVERURL
      - SERVERPORT=$ENV_SERVERPORT
      - PEERS=0
      - PEERDNS=$ENV_PEERDNS
      - INTERNAL_SUBNET=$ENV_INTERNAL_SUBNET
      - ALLOWEDIPS=0.0.0.0/0,::/0
    volumes:
      - ./config:/config
      - ./clients:/config/clients
      - /lib/modules:/lib/modules
    entrypoint: ["/config/scripts/setup-path.sh"]
    ports:
      - $ENV_SERVERPORT:$ENV_SERVERPORT/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.forwarding=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
